dev:
	mode=dev deno run --allow-all --import-map importmap.json --no-check --unstable --watch server.ts

start:
	deno run deno run --allow-all --import-map importmap.json --unstable server.ts

cache:
	deno cache --import-map=importmap.json --reload --no-check server.ts