name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # Setup node for building tailwind styles
      - name: Use Node@14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        
      # Setup deno for task run
      - name: Use Deno@latest
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run build
        run: cd examples/website && deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "micro"
          import-map: "importmap.json"
          entrypoint: "./examples/website/server.ts" 
